//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erp_universidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleservicio
    {
        public int iddetalleser { get; set; }
        public Nullable<int> idservicio { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
        public Nullable<int> idexplotacion { get; set; }
        public Nullable<int> idcta { get; set; }
        public Nullable<int> idproducto { get; set; }
    
        public virtual ctascontables ctascontables { get; set; }
        public virtual unidadexplot unidadexplot { get; set; }
        public virtual producto producto { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
