//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erp_universidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class erp_universidadEntities : DbContext
    {
        public erp_universidadEntities()
            : base("name=erp_universidadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<comprador> comprador { get; set; }
        public virtual DbSet<contrato> contrato { get; set; }
        public virtual DbSet<ctascontables> ctascontables { get; set; }
        public virtual DbSet<detallefactura> detallefactura { get; set; }
        public virtual DbSet<detalleservicio> detalleservicio { get; set; }
        public virtual DbSet<detalord> detalord { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<orden_compra> orden_compra { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<recepcion> recepcion { get; set; }
        public virtual DbSet<sede> sede { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<solicitud> solicitud { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<unidadexplot> unidadexplot { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
