//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erp_universidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        public int idsolicitud { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fecha_rec { get; set; }
        public Nullable<System.DateTime> fecha_apr { get; set; }
        public Nullable<System.DateTime> fecha_anu { get; set; }
        public string estado { get; set; }
        public Nullable<int> idsede { get; set; }
        public Nullable<int> idempleado { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual sede sede { get; set; }
    }
}
