//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erp_universidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int idusuarios { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string email_corporativo { get; set; }
        public Nullable<System.DateTime> fecha_cambio_pass { get; set; }
        public string permiso { get; set; }
        public Nullable<int> idempleado { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
