//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcongreso.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividades
    {
        public int idactividad { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string rol_creacion { get; set; }
        public string estado { get; set; }
        public Nullable<int> idlistaeq { get; set; }
        public Nullable<int> idasistencias { get; set; }
        public Nullable<int> idsala { get; set; }
        public Nullable<System.DateTime> fec_inicio { get; set; }
        public Nullable<System.DateTime> fec_Fin { get; set; }
        public string Nombre { get; set; }
        public string rol_responsable { get; set; }
    
        public virtual listaequipos listaequipos { get; set; }
        public virtual sala sala { get; set; }
        public virtual asistencias asistencias { get; set; }
    }
}
