//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcongreso.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_list_equipos
    {
        public int intdetalleeq { get; set; }
        public string estado { get; set; }
        public Nullable<int> idEquipo { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
