//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcongreso.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_asistencias
    {
        public int intdetasis { get; set; }
        public string estado { get; set; }
        public string DNI { get; set; }
        public string codigo { get; set; }
    }
}
